language: php

cache:
  yarn: true
  directories:
    - node_modules
    - vendor

install:
  - composer install

before_script:
  - if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE tests;' -U postgres; fi
  - if [ '$DB' = 'mariadb' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS tests;'; fi

script:
  - ./vendor/bin/phpunit

matrix:
  include:
    - php: 7.0
      env: DB=mariadb
      addons:
        - mariadb: 10.2
    - php: 7.0
      env: DB=pgsql
      services: postgresql
    - php: 7.0
      env: DB=sqlite
    - php: 7.1
      env: DB=mariadb
      addons:
        - mariadb: 10.2
    - php: 7.1
      env: DB=pgsql
      services: postgresql
    - php: 7.1
      env: DB=sqlite
    - php: 7.2
      env: DB=mariadb
      addons:
        - mariadb: 10.2
    - php: 7.2
      env: DB=pgsql
      services: postgresql
    - php: 7.2
      env: DB=sqlite
    - node_js: 8
      sudo: required
      language: node_js
      addons:
        chrome: stable
      install:
        - yarn
      before_script:
        - sudo chown root /opt/google/chrome/chrome-sandbox
        - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
      script:
        - yarn lint:check
        - yarn test
