language: php

cache:
  yarn: true
  directories:
    - vendor

install:
  - composer install

before_script:
  - if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE tests;' -U postgres; fi
  - if [ '$DB' = 'mariadb' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS tests;'; fi

script:
  - ./vendor/bin/phpunit

matrix:
  include:
    - php: 7.0
      env: DB=mariadb
      addons:
        - mariadb: 10.2
    - php: 7.0
      env: DB=pgsql
      services: postgresql
    - php: 7.0
      env: DB=sqlite
    - php: 7.1
      env: DB=mariadb
      addons:
        - mariadb: 10.2
    - php: 7.1
      env: DB=pgsql
      services: postgresql
    - php: 7.1
      env: DB=sqlite
    - php: 7.2
      env: DB=mariadb
      addons:
        - mariadb: 10.2
    - php: 7.2
      env: DB=pgsql
      services: postgresql
    - php: 7.2
      env: DB=sqlite
    - node_js: 8
      language: node_js
      install:
        - yarn
      before_script:
        - echo 'Testing UI code' > /dev/null
      script:
        - yarn lint:check
        - yarn test
